[database]
# Database file path
# path = "data/raw/mlb_betting.duckdb"  # Migrated to PostgreSQL

[schemas]
# Pipeline zone schemas
raw = "raw_data"
staging = "staging"
curated = "curated"
# Legacy schema
legacy = "splits"

[pipeline]
# Pipeline configuration
enable_staging = true
enable_curated = true
auto_promotion = true  # Auto-move data through pipeline stages
validation_enabled = true
quality_threshold = 0.8  # Minimum quality score for promotion

[pipeline.zones]
raw_enabled = true
staging_enabled = true
curated_enabled = false  # Enable after testing

[tables]
# Main table for MLB betting splits
mlb_betting_splits = "raw_mlb_betting_splits"

# Legacy table (for backward compatibility)
legacy_splits = "splits"

[data_sources]
# Source identifiers
sbd = "SBD"  # SportsBettingDime
vsin = "VSIN"  # VSIN

[api]
# SportsBettingDime API configuration
sbd_url = "https://srfeeds.sportsbettingdime.com/v2/matchups/mlb/betting-splits"
sbd_books = ["betmgm", "bet365", "fanatics", "draftkings", "caesars", "fanduel"] 