-- Backup of timing_analysis.timing_bucket_performance
-- Created: 2025-07-09T17:17:50.201345
-- Record count: 3

-- Table structure
-- id: integer
-- timing_bucket: character varying
-- source: character varying
-- book: character varying
-- split_type: character varying
-- strategy_name: character varying
-- analysis_start_date: date
-- analysis_end_date: date
-- total_bets: integer
-- wins: integer
-- losses: integer
-- pushes: integer
-- total_units_wagered: numeric
-- total_profit_loss: numeric
-- avg_odds_at_recommendation: numeric
-- avg_closing_odds: numeric
-- win_rate: numeric
-- roi_percentage: numeric
-- confidence_level: character varying
-- created_at: timestamp with time zone
-- updated_at: timestamp with time zone

-- Data backup would go here
-- Use pg_dump for actual data backup in production
