-- Backup of mlb_betting.spreads
-- Created: 2025-07-09T17:17:50.137309
-- Record count: 9595

-- Table structure
-- id: integer
-- game_id: integer
-- sportsbook: character varying
-- home_spread: numeric
-- away_spread: numeric
-- home_spread_price: integer
-- away_spread_price: integer
-- odds_timestamp: timestamp with time zone
-- opening_home_spread: numeric
-- opening_away_spread: numeric
-- opening_home_spread_price: integer
-- opening_away_spread_price: integer
-- closing_home_spread: numeric
-- closing_away_spread: numeric
-- closing_home_spread_price: integer
-- closing_away_spread_price: integer
-- home_bets_count: integer
-- away_bets_count: integer
-- home_bets_percentage: numeric
-- away_bets_percentage: numeric
-- home_money_percentage: numeric
-- away_money_percentage: numeric
-- sharp_action: character varying
-- reverse_line_movement: boolean
-- steam_move: boolean
-- winning_side: character varying
-- profit_loss: numeric
-- home_cover: boolean
-- margin_of_victory: integer
-- source: character varying
-- data_quality: character varying
-- created_at: timestamp with time zone
-- updated_at: timestamp with time zone
-- game_datetime: timestamp with time zone
-- home_team: character varying
-- away_team: character varying

-- Data backup would go here
-- Use pg_dump for actual data backup in production
